/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ApplyBounty
 * @category generated
 */
export const applyBountyStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'ApplyBountyInstructionArgs'
)
/**
 * Accounts required by the _applyBounty_ instruction
 *
 * @property [**signer**] freelancer
 * @property [] freelanceAccount
 * @property [_writable_] bountyAccount
 * @category Instructions
 * @category ApplyBounty
 * @category generated
 */
export type ApplyBountyInstructionAccounts = {
  freelancer: web3.PublicKey
  freelanceAccount: web3.PublicKey
  bountyAccount: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const applyBountyInstructionDiscriminator = [
  56, 213, 22, 91, 205, 51, 68, 251,
]

/**
 * Creates a _ApplyBounty_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ApplyBounty
 * @category generated
 */
export function createApplyBountyInstruction(
  accounts: ApplyBountyInstructionAccounts,
  programId = new web3.PublicKey('CnMMyfQSGk7h6YNf2uLmBuLpfBKuMTYPct6PmFMM3P24')
) {
  const [data] = applyBountyStruct.serialize({
    instructionDiscriminator: applyBountyInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.freelancer,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.freelanceAccount,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.bountyAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
