/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category AssignFreelancer
 * @category generated
 */
export const assignFreelancerStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'AssignFreelancerInstructionArgs'
)
/**
 * Accounts required by the _assignFreelancer_ instruction
 *
 * @property [_writable_, **signer**] authority
 * @property [] freelanceAccount
 * @property [_writable_] multiSig
 * @property [_writable_] bountyAccount
 * @category Instructions
 * @category AssignFreelancer
 * @category generated
 */
export type AssignFreelancerInstructionAccounts = {
  authority: web3.PublicKey
  freelanceAccount: web3.PublicKey
  multiSig: web3.PublicKey
  bountyAccount: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const assignFreelancerInstructionDiscriminator = [
  27, 101, 101, 33, 185, 240, 49, 35,
]

/**
 * Creates a _AssignFreelancer_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category AssignFreelancer
 * @category generated
 */
export function createAssignFreelancerInstruction(
  accounts: AssignFreelancerInstructionAccounts,
  programId = new web3.PublicKey('CnMMyfQSGk7h6YNf2uLmBuLpfBKuMTYPct6PmFMM3P24')
) {
  const [data] = assignFreelancerStruct.serialize({
    instructionDiscriminator: assignFreelancerInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.freelanceAccount,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.multiSig,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.bountyAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
