/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ClaimBounty
 * @category generated
 */
export const claimBountyStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'ClaimBountyInstructionArgs'
)
/**
 * Accounts required by the _claimBounty_ instruction
 *
 * @property [_writable_, **signer**] claimer
 * @property [_writable_] bountyAccount
 * @property [_writable_] bountyTokenAccount
 * @property [_writable_] claimerTokenAccount
 * @property [] usdcMint
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category ClaimBounty
 * @category generated
 */
export type ClaimBountyInstructionAccounts = {
  claimer: web3.PublicKey
  bountyAccount: web3.PublicKey
  bountyTokenAccount: web3.PublicKey
  claimerTokenAccount: web3.PublicKey
  usdcMint: web3.PublicKey
  systemProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const claimBountyInstructionDiscriminator = [
  225, 157, 163, 238, 239, 169, 75, 226,
]

/**
 * Creates a _ClaimBounty_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ClaimBounty
 * @category generated
 */
export function createClaimBountyInstruction(
  accounts: ClaimBountyInstructionAccounts,
  programId = new web3.PublicKey('CnMMyfQSGk7h6YNf2uLmBuLpfBKuMTYPct6PmFMM3P24')
) {
  const [data] = claimBountyStruct.serialize({
    instructionDiscriminator: claimBountyInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.claimer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.bountyAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.bountyTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.claimerTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.usdcMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
