/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category StakeSkillset
 * @category generated
 */
export type StakeSkillsetInstructionArgs = {
  skill: string
  stakeAmount: beet.bignum
}
/**
 * @category Instructions
 * @category StakeSkillset
 * @category generated
 */
export const stakeSkillsetStruct = new beet.FixableBeetArgsStruct<
  StakeSkillsetInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['skill', beet.utf8String],
    ['stakeAmount', beet.u64],
  ],
  'StakeSkillsetInstructionArgs'
)
/**
 * Accounts required by the _stakeSkillset_ instruction
 *
 * @property [_writable_, **signer**] staker
 * @property [_writable_] freelanceAccount
 * @property [] usdcMint
 * @property [_writable_] stakerTokenAccount
 * @property [_writable_] skillStake
 * @property [_writable_] skillStakeTokenAccount
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category StakeSkillset
 * @category generated
 */
export type StakeSkillsetInstructionAccounts = {
  staker: web3.PublicKey
  freelanceAccount: web3.PublicKey
  usdcMint: web3.PublicKey
  stakerTokenAccount: web3.PublicKey
  skillStake: web3.PublicKey
  skillStakeTokenAccount: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const stakeSkillsetInstructionDiscriminator = [
  26, 234, 4, 3, 142, 192, 170, 40,
]

/**
 * Creates a _StakeSkillset_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category StakeSkillset
 * @category generated
 */
export function createStakeSkillsetInstruction(
  accounts: StakeSkillsetInstructionAccounts,
  args: StakeSkillsetInstructionArgs,
  programId = new web3.PublicKey('CnMMyfQSGk7h6YNf2uLmBuLpfBKuMTYPct6PmFMM3P24')
) {
  const [data] = stakeSkillsetStruct.serialize({
    instructionDiscriminator: stakeSkillsetInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.staker,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.freelanceAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.usdcMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.stakerTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.skillStake,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.skillStakeTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
