/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link Freelancer}
 * @category Accounts
 * @category generated
 */
export type FreelancerArgs = {
  bump: number
  freelancer: web3.PublicKey
  userMetadata: string
  skills: string[]
}

export const freelancerDiscriminator = [85, 117, 113, 118, 145, 222, 67, 98]
/**
 * Holds the data for the {@link Freelancer} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Freelancer implements FreelancerArgs {
  private constructor(
    readonly bump: number,
    readonly freelancer: web3.PublicKey,
    readonly userMetadata: string,
    readonly skills: string[]
  ) {}

  /**
   * Creates a {@link Freelancer} instance from the provided args.
   */
  static fromArgs(args: FreelancerArgs) {
    return new Freelancer(
      args.bump,
      args.freelancer,
      args.userMetadata,
      args.skills
    )
  }

  /**
   * Deserializes the {@link Freelancer} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [Freelancer, number] {
    return Freelancer.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Freelancer} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<Freelancer> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Freelancer account at ${address}`)
    }
    return Freelancer.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'CnMMyfQSGk7h6YNf2uLmBuLpfBKuMTYPct6PmFMM3P24'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, freelancerBeet)
  }

  /**
   * Deserializes the {@link Freelancer} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Freelancer, number] {
    return freelancerBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Freelancer} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return freelancerBeet.serialize({
      accountDiscriminator: freelancerDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Freelancer} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: FreelancerArgs) {
    const instance = Freelancer.fromArgs(args)
    return freelancerBeet.toFixedFromValue({
      accountDiscriminator: freelancerDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Freelancer} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: FreelancerArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Freelancer.byteSize(args),
      commitment
    )
  }

  /**
   * Returns a readable version of {@link Freelancer} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      freelancer: this.freelancer.toBase58(),
      userMetadata: this.userMetadata,
      skills: this.skills,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const freelancerBeet = new beet.FixableBeetStruct<
  Freelancer,
  FreelancerArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['freelancer', beetSolana.publicKey],
    ['userMetadata', beet.utf8String],
    ['skills', beet.array(beet.utf8String)],
  ],
  Freelancer.fromArgs,
  'Freelancer'
)
