/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link SkillStake}
 * @category Accounts
 * @category generated
 */
export type SkillStakeArgs = {
  bump: number
  freelancer: web3.PublicKey
  skill: string
  stakeAmounts: beet.bignum[]
  stakers: web3.PublicKey[]
  totalSkillStake: beet.bignum
}

export const skillStakeDiscriminator = [165, 213, 19, 76, 3, 168, 144, 239]
/**
 * Holds the data for the {@link SkillStake} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class SkillStake implements SkillStakeArgs {
  private constructor(
    readonly bump: number,
    readonly freelancer: web3.PublicKey,
    readonly skill: string,
    readonly stakeAmounts: beet.bignum[],
    readonly stakers: web3.PublicKey[],
    readonly totalSkillStake: beet.bignum
  ) {}

  /**
   * Creates a {@link SkillStake} instance from the provided args.
   */
  static fromArgs(args: SkillStakeArgs) {
    return new SkillStake(
      args.bump,
      args.freelancer,
      args.skill,
      args.stakeAmounts,
      args.stakers,
      args.totalSkillStake
    )
  }

  /**
   * Deserializes the {@link SkillStake} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [SkillStake, number] {
    return SkillStake.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link SkillStake} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<SkillStake> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find SkillStake account at ${address}`)
    }
    return SkillStake.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'CnMMyfQSGk7h6YNf2uLmBuLpfBKuMTYPct6PmFMM3P24'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, skillStakeBeet)
  }

  /**
   * Deserializes the {@link SkillStake} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [SkillStake, number] {
    return skillStakeBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link SkillStake} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return skillStakeBeet.serialize({
      accountDiscriminator: skillStakeDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link SkillStake} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: SkillStakeArgs) {
    const instance = SkillStake.fromArgs(args)
    return skillStakeBeet.toFixedFromValue({
      accountDiscriminator: skillStakeDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link SkillStake} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: SkillStakeArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      SkillStake.byteSize(args),
      commitment
    )
  }

  /**
   * Returns a readable version of {@link SkillStake} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      freelancer: this.freelancer.toBase58(),
      skill: this.skill,
      stakeAmounts: this.stakeAmounts,
      stakers: this.stakers,
      totalSkillStake: (() => {
        const x = <{ toNumber: () => number }>this.totalSkillStake
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const skillStakeBeet = new beet.FixableBeetStruct<
  SkillStake,
  SkillStakeArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['freelancer', beetSolana.publicKey],
    ['skill', beet.utf8String],
    ['stakeAmounts', beet.array(beet.u64)],
    ['stakers', beet.array(beetSolana.publicKey)],
    ['totalSkillStake', beet.u64],
  ],
  SkillStake.fromArgs,
  'SkillStake'
)
